usage: "注意：本软件需要自备视频播放源方能正常使用"
application:
  subdomain: katelyatv
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://katelyatv:3000/
services:
  katelyatv:
    # upstream: ghcr.io/katelya77/katelyatv:latest@sha256:ad04f71a436a580b1ab5a8e69a6c568c58f7990413b52d0ddc79ea5d814a7208
    image: registry.lazycat.cloud/czyt/katelya77/katelyatv:bc0fb7a8e789ecfc
    environment:
      - USERNAME={{ .U.admin_username }}
      - PASSWORD={{.U.admin_password}}
      - NEXT_PUBLIC_ENABLE_REGISTER={{.U.enable_register}}
      - NEXT_PUBLIC_STORAGE_TYPE=redis
      - REDIS_URL=redis://katelyatv-redis:6379
    depends_on:
      - katelyatv-redis
  katelyatv-redis:
    # upstream: library/redis:7.4-alpine
    image: registry.lazycat.cloud/czyt/library/redis:feb21bfd39585516
    binds:
      - /lzcapp/var/redis:/data
